; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

[env:pcb]
; an environment for the PCB, which runs on the Teensy 4.1 (excluding the Arduino Nano for now)
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 921600



[env:uart]
; build environment for UART setup on Arduino UNO R4 WiFi
platform = renesas-ra
board = uno_r4_wifi
framework = arduino

; compile/upload the code responsible for UART communication
; UNO R4 WiFi keeps 5V I/O compatibility, but it is not the classic AVR UNO
targets = upload, monitor
monitor_speed = 921600

build_src_filter =
    -<*>
    +<cubemars_uart/**>

;dd
[env:can]
;build environment for CAN setup
extends = env:pcb
build_src_filter =
    -<*>
    +<cubemars_can/**>
targets = upload, monitor

[env:test_teensy]
;build environment for CAN setup
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<test_teensy/**>
targets = upload, monitor